config/routes.rb
Crawly::Application.routes.draw do
  namespace :admin do
    root :to => 'dashboard#index'
    resources :items
    resources :rooms
  end

  resource :inventory, only: :show
  resources :rooms do
    resource :move
    resource :pick_up
    resource :drop
  end

  root :to => 'dashboard#index'
end

app/models/drop.rb
class Drop
  attr_accessor :room, :item, :user
  def initialize(options={})
    self.room = options[:room]
    self.item = options[:item]
    self.user = options[:user]
  end

  def valid?
    user.items.include?(item)
  end

  def execute
    return unless valid?

    item.user = nil
    item.room = room
    item.save
  end
end

app/models/exit.rb
class Exit < ActiveRecord::Base
  attr_accessible :destination_id, :name, :room_id

  belongs_to :room
  belongs_to :destination, class_name: 'Room'
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :name, :room_id
  belongs_to :room
  belongs_to :user

  before_update :unset_user_if_room_changed

  protected

  def unset_user_if_room_changed
    if room.present? && self.user.present?
      self.user = nil
    end
  end
end

app/models/move.rb
class Move
  attr_accessor :room, :exit, :user

  def initialize(options={})
    self.room = options[:room]
    self.exit = options[:exit]
    self.user = options[:user]
  end

  def valid?
    user.room == room && exit.room == room
  end

  def execute
    return unless valid?

    user.room = exit.destination
    user.save
  end
end

app/models/pick_up.rb
class PickUp
  attr_accessor :room, :item, :user
  def initialize(options={})
    self.room = options[:room]
    self.item = options[:item]
    self.user = options[:user]
  end

  def valid?
    room.items.include?(item)
  end

  def execute
    return unless valid?

    item.user = user
    item.room = nil
    item.save
  end
end

app/models/room.rb
class Room < ActiveRecord::Base
  attr_accessible :name, :description, :exits_attributes

  has_many :exits
  has_many :items

  accepts_nested_attributes_for :exits, reject_if: :all_blank, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :room
  has_many :items
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin'
  # YAGNI, sure, but of course admin has auth
  # and it will be nice to have admin controllers
  # have a shared base controller when that time
  # comes
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  def index
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::BaseController
  inherit_resources
  actions :index, :new, :create, :edit, :update
end

app/controllers/admin/rooms_controller.rb
class Admin::RoomsController < Admin::BaseController
  inherit_resources
  actions :index, :new, :create, :edit, :update

  def new
    new! do
      @room.exits.build
    end
  end

  def edit
    edit! do
      @room.exits.build
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  def current_user
    if session[:user_id].present?
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = User.create.tap{|user| session[:user_id] = user.id }
    end
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    current_user.room ||= Room.first
    current_user.save
    redirect_to(current_user.room)
  end
end

app/controllers/drops_controller.rb
class DropsController < ApplicationController
  def create
    room = Room.find(params[:room_id])
    item = current_user.items.find(params[:item_id])
    Drop.new(:room => room, :item => item, :user => current_user).execute

    redirect_to room_path(room)
  end
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  def create
    @room = Room.find(params[:room_id])
    @exit = @room.exits.find(params[:exit_id])

    Move.new(user: current_user, room: @room, exit: @exit).execute

    redirect_to current_user.room
  end
end

app/controllers/pick_ups_controller.rb
class PickUpsController < ApplicationController
  def create
    room = Room.find(params[:room_id])
    item = room.items.find(params[:item_id])
    PickUp.new(:room => room, :item => item, :user => current_user).execute
    redirect_to room_path(room)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_filter :load_room

  def show
    @exits = @room.exits
    @items = @room.items
  end

  protected

  def load_room
    @room = Room.find(params[:id])
    redirect_to room_path(current_user.room) unless current_user.room == @room
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/dashboard/index.html.haml
Herp Derp Imma Dashboard

app/views/admin/items/_form.html.haml
= simple_form_for [:admin, @item], class: 'form-horizontal' do |f|
  = f.input :name
  = f.input :room_id, as: :select, collection: Room.all

  = f.submit

app/views/admin/items/edit.html.haml
- provide(:header) { 'Edit Item' }

.span4
  = render 'form'

app/views/admin/items/index.html.haml
- provide(:header) { 'Items' }

%table.table.table-bordered.table-striped
  %thead
    %tr
      %td Name
      %td Room
      %td User ID
      %td Actions
  %tbody
    - @items.each do |item|
      %tr{id: "item#{item.id}"}
        %td= item.name
        %td= item.room.try(:name)
        %td= item.user.try(:id)
        %td= link_to 'Edit', edit_admin_item_path(item)

= link_to 'New Item', new_admin_item_path, class: 'btn btn-primary new-button'

app/views/admin/items/new.html.haml
- provide(:header) { 'New Item' }

.span4
  = render 'form'

app/views/admin/rooms/_form.html.haml
.span4
  = simple_form_for [:admin, @room], class: 'form-horizontal' do |f|
    = f.input :name
    = f.input :description

    = f.label :exits
    %ul.exits
      = f.simple_fields_for :exits do |exit|
        %li
          %a.close{href: '#'} X
          = exit.input :name
          = exit.input :destination_id, as: :select, collection: Room.all
          = exit.input :_destroy, as: :hidden, value: '0', input_html: { class: 'destroy-field' }

    = f.submit

:javascript
  new crawly.admin.views.RoomFormView({el: 'form'});

app/views/admin/rooms/edit.html.haml
- provide(:header) { "Edit #{@room.name}" }
= render 'form'

app/views/admin/rooms/index.html.haml
- provide(:header) { 'Rooms' }

%table.table.table-bordered.table-striped
  %thead
    %tr
      %td Name
      %td Description
      %td Actions
  %tbody
    - @rooms.each do |room|
      %tr{id: "room#{room.id}"}
        %td= room.name
        %td= room.description
        %td= link_to 'Edit', edit_admin_room_path(room)

= link_to 'New Room', new_admin_room_path, class: 'btn btn-primary new-button'

app/views/admin/rooms/new.html.haml
- provide(:header) { 'New Room' }
= render 'form'

app/views/dashboard/index.html.erb
DURR

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title Crawly Admin
  = stylesheet_link_tag 'admin', media: 'all'
  = javascript_include_tag 'admin/application'
  = csrf_meta_tags

  %body
    .container
      .page-header
        - header = yield(:header)
        %h2= header.present? ? header : 'Admin'
      .row-fluid
        .span3
          = render 'layouts/admin/nav'
        .span9
          - if notice
            .alert= notice
          = yield

app/views/layouts/admin/_nav.html.haml
.well
  %ul
    %li= link_to 'Items', admin_items_path
    %li= link_to 'Rooms', admin_rooms_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Crawly
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .header
      = render 'layouts/application/header'
    .container
      .row-fluid
        .span8
          = yield
        .span4
          = render 'layouts/application/inventory'

app/views/layouts/application/_header.html.haml
.page-header
  %h1
    Butt City
    %small the game

app/views/layouts/application/_inventory.html.haml
.well.inventory
  %h2 Inventory

  %ul.items
    - current_user.items.each do |item|
      %li
        = "A #{item.name}"
        = button_to 'Drop', room_drop_path(current_user.room, item_id: item.id), class: 'btn btn-warning'

app/views/rooms/show.html.haml
.room
  %h1= @room.name
  .description
    %strong Description:
    = @room.description

  - unless @items.empty?
    .items
      %strong #{pluralize(@items.size, 'Item', 'Items')} here:
      .accordion
      - @items.each do |item|
        .accordion-group
          .accordion-heading
            .accordion-toggle{id: "item-#{item.id}-header", 'data-toggle' => 'collapse', 'data-target' => "#item-#{item.id}-body" }
              %span.item-header
                A #{item.name}
                %i.icon-eye-open
          .accordion-body.collapse{id: "item-#{item.id}-body"}
            .accordion-inner
              = button_to 'Pick Up', room_pick_up_path(@room, item_id: item.id), class: 'btn btn-warning'

  .exits
    - @exits.each do |exit|
      = button_to exit.name, room_move_path(@room, exit_id: exit.id), class: 'btn btn-danger'

:javascript
  new crawly.views.RoomView({el: 'body'});